groups:
- name: Infraestructura_Tecnica
  rules:
  - alert: HostDown
    expr: up == 0
    for: 1m
    labels:
      severity: critical
      audience: technical
    annotations:
      summary: "Servidor {{ $labels.instance }} inalcanzable"
      description: "El agente no responde desde hace 1 minuto."

- name: SLA_Negocio
  rules:
  - alert: PortalCiudadanoCaido
    expr: probe_success{job="ansd-public-portals"} == 0
    for: 2m
    labels:
      severity: critical
      audience: executive # Esto dispara la notificaci  n a gerencia
    annotations:
      summary: "Ca  da del Portal Ciudadano"
      description: "El sitio web p  blico no responde a las peticiones HTTP."
