groups:
  - name: ANSD_Global_Rules
    rules:
      # ALERTA TECNICA: Uso de disco (No molesta a gerencia)
      - alert: HostHighDiskUsage
        expr: (node_filesystem_free_bytes / node_filesystem_size_bytes) * 100 < 10
        for: 5m
        labels:
          severity: warning
          audience: technical
        annotations:
          summary: "Poco espacio en disco en {{ $labels.instance }}"
          description: "El disco tiene menos del 10% disponible."

      # ALERTA GERENCIAL + TECNICA: Caida de portal (Alto Nivel)
      - alert: PortalCiudadanoDown
        expr: probe_success{job="ansd-portals"} == 0
        for: 1m
        labels:
          severity: critical
          audience: executive
        annotations:
          summary: "CR ^mTICO: Portal de Servicios No Disponible"
          description: "El portal ciudadano ha dejado de responder. Impacto inmediato en la poblaci  n."